sudo: false
language: python
python:
  - '2.7'
cache:
  directories:
  - $HOME/gcloud/
env:
  global:
    - PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/client_secrets.json
    - secure: "ILXZQVz32tbzGb8iwvQEMPreKNRO/kXQAalwqjK/6CEyn1S0b35+sFNvYkMb7vFTixStJA9Jks+iJ/CEXTySNcJLhU89wiZEOUnRz+VdDRbFmIJ/+w3N/tlYjFCxGTL1jtTjwPEuxUjVQxrJ1B6MmRHTdlvXrpFyd1PTsn5Uyxxc0DdB3q5QDkn3kfX5kKZ7W4AR8LgDe+wHfs29kmhvnmk+9ADh9yYx+63xobKGJJBQDDEbR9M4AKAm71oImjmMpkz5Fzxvi4VvkLccDcKGEUeN+OWFWiOAmjEz0UCar5xBE3/Hzlc5DGXLBFfRg0AH47lZj04AeQri3hTW26YVZ2uyPOl19q9LLGkrJKTKf+Ov44qsubAs4/qGAlksu74nvGmKBKOf/kUYJ52a2cm0fuIkZJY4y99F4Mp3pDoFmYecAmWpAvugDBPpClY9l+5guccjoIe0bnErZF4xrTY19TLIV+RjeBqJ6MfPD5SybW+PU8Sk1/YQTLPT9WCRWm5vxXaJ43jPJSVNufqoyGhW7lLeCf3xpZUgm9m/aipOVPyTg74h9IrhcMLy+tTalgmrQwZOLnSybTxAQA+9LFEHv+1PcNa5hYkKlJ7x/XQ83q4R4JrLs3907GSYo51+B3RK5u/bG659UYPMmCYRqdDrbDTqrBQqoNGxEruT/W5pChU="
    - secure: "USySRXCv0jiqrSbc38WSjW3A55iXJPoG3VSoCa2HaZJAADQ3ALjBYI8wq+ZaC7IlffxLA7vHp5S6aq5xfI/GGrhKXpTq2TQcbbq4dzU2yaX/tD4XFrQuMvsI5oHQz/ys+zCccUa4uLcPetDTvuCcvtJPdr/v4aNsou+35JZ/RzyQoEXjVFtt+l+JDu8jNOrl9LgXX3nN5/wvU9bHSMpLJgJaXGpF4WhkANtY72V+Ddwj6ZhpC5hlBwKjVx8rZvphemG43uCgU65my+Nodx7l4MLk18d/nIINVkpKuoXv2wYO+A85Lt4qHkHAya+FGVtFe7Pju2M0QcDwVws+c/M+7UsKLVdl1a6o5CAJs8heAt08jZae2ro8cJiJjiSGFPjugRiFf4LWqWYiynY1Qk9ooKSjFqpSib1Myk3Mmss7Eqis07YO7S44cqCSg4JXKQialduBIC7d+UYJan9YziBUmDr+YkKTy2rTHmiqUB95TDS+G0+JCueXmNWX1Fdpy+20osoTcBbS31NFCDLMTJ/QS1QzU7OxjEd5WwQZ8WiWSGE032wyHt9rMaL9c8h9G35f5T+H5CQjaDO0wUUU0B4xZ9+REsocHELcuaVBh2yfJvLJP6ln9vxb2pdVDAytHFbZ7KH4JQz5yeyWsLabCDr+ELzos8EhQGXwJ/qvDPz9IfI="
    - secure: "DnVaMAqBADOgIaUamB5TnWp6+IR/BjemHRX4wjkKViGwac7tvnqCUmKcOcZBHyPfn/DxKaC3pXW47eJOGibQQtpO+RpOkKgqaMHhQn87LZ5guGfamrYTIkUlu0qjSWKjF7zynwfFhI0wBD99CZv+sIE48epvN6G+zLXUvFoDfBE26b1B2HlRYIFx9ZvDVexArg+EJ0hQmVg5AwPa6E7ABjrvShcYsGmf9mqfzP7hKgxQvItlGJIUL+zcoz54nL6SgLJypbDSmTf3Le7hd3Zfv4R7CcyGcPjnhEA9O4xXBrCeGMvmPyS2cQsPCVrxrc7E5PvXDknSZMsNOqLbQ9p9MBhcXfQbnu/HwbBzpRuWupXnavn7RXhzc2qS2L/X9Svy81ObvmfbAWziQ2ddIHxv4W+GfVD4xcm9XcAvJw9IHDMRrPx+oTgAw/sBz7kGmtOD7Omj/nDxfNV7QEr4QksbIkpMOjXyMU3oCWrxcvjJJS5o/oqhnPwCDjyWpulIK1HxEHGR5SPDUYAmoriI6wQKxRcxCT1tbW9YO517WnYeKf12sSYTnkR6slx1nhdBRLACJEG7KuIADrc/CsXP8YC8cN9za+xEkno+GeHmkL5kJyqBohX15uL+NvZHwlMkNbW/2Rszi1meW11rvqmZ4uHOZ57eB9+jUs8NnbF/o2ulOv0="
    - secure: "D5gE1Lv7VgkbO3uCK0eMvoPGj8o7Qam77qb3DdsxjeWETmxBzkvmzzYx2mTggyKJMyZFP+1DV01aDybR6I+F88Vp1UxS4nxE82cjjUAik8LbK4LxQ0T4dmvgc+28551V3fysGRfB54tHuYkD3v6J+C34KdotVU9X2rtLKF2jay78b0VV2KKil2Nz0k5Qzrv6x7Lx4aMynVqQLY1MAc+LytNFXnxmyLJ5e3E50OEVL1c0EsAPUHze1g/KcMQV3vdch/Q0nZUTm7ShbmW5X9h0hMYiwHZF4LMA9BczUOqciFUg3BdjRM8P2akOhAPjJekr8ue6cIDnl7bdMgExSqEh37I7iMMm9dXYK000Am4dwW7a0puW+u336cDCuMdsZIEz/btSCSmsRMDSDFYBo69IpYXPDucZIU7B3pWzyjd/3ycl2Obfr6D5tGVLdAYHOcR35sesguIUVLRR07miswQiX+FyDVy2eyjLdQM1DAdcv0/HhCmTelkcZRb5jqU/SvkIO7Rf/ml0PRINuwYu/2sAwUUMraD/FHKAmggNDh848LPPr5GANt2ESCgvuuINcRMMCJ3LT6+xllkvgs7HHhx2Rctc1tio6sL1k2GnzX7aU8+wklkDaaDdsTWaCEzQPgShN9CavVxSlQyYyNT7NLt+RatT8Qs4IuIT8ZcdFWRFB/M="
    - versionlabel=$(git rev-parse --abbrev-ref HEAD)-$(date -u +"%Y%m%d-%H%M%S")

before_install:
  - openssl aes-256-cbc -K $encrypted_0f97f4d13dc8_key -iv $encrypted_0f97f4d13dc8_iv
    -in client_secrets.json.enc -out client_secrets.json -d
  - if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then mkdir -p $HOME/gcloud && wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
    --directory-prefix=$HOME/gcloud && cd $HOME/gcloud && tar xzf google-cloud-sdk.tar.gz
    && printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh && cd $TRAVIS_BUILD_DIR;
    fi
  - gcloud -q components update
  - if [ -a client_secrets.json ]; then gcloud -q auth activate-service-account --key-file
    client_secrets.json; fi
  - gcloud config set project causal-flame-94214

install:
  - pip install -t lib -r requirements.txt
  - pip install virtualenvwrapper
  - source virtualenvwrapper.sh
  - add2virtualenv ./lib
  - pip install coveralls

before_script:
  - mysql -e 'create database migrate_dev;'
  - TARGET_DB=$TEST_DB python main.py db upgrade

script:
  # - python testrunner.py $HOME/gcloud/google-cloud-sdk ./tests
  - coverage run testrunner.py $HOME/gcloud/google-cloud-sdk ./tests

after_success:
  - coveralls
  - gcloud -q preview app deploy app.yaml --version=1
  # commenting this out since the dedicated ip addy was removed to avoid costs!
  # - TARGET_DB=$PROD_DB python main.py db upgrade
