sudo: false
language: python
python:
        - '2.7'
cache:
  directories:
        - $HOME/gcloud/
env:
        - PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/client_secrets.json

before_install:
        # ENCRYPT YOUR PRIVATE KEY (If you need authentication)
        # 1. Install and login to the Travis CLI:
        #       $ gem install travis
        #       $ travis login
        # 2. Move your json private key to client_secrets.json
        # 3. Run:
        #       $ travis encrypt-file client_secrets.json --add
        # 4. Commit changes:
        #       $ git add client_secrets.json.enc
        #       $ git commit client_secrets.json.enc .travis.yml

        - openssl aes-256-cbc -K $encrypted_0f97f4d13dc8_key -iv $encrypted_0f97f4d13dc8_iv -in client_secrets.json.enc -out client_secrets.json -d

        - if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then
                mkdir -p $HOME/gcloud &&
                wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --directory-prefix=$HOME/gcloud &&
                cd $HOME/gcloud &&
                tar xzf google-cloud-sdk.tar.gz &&
                printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh &&
                cd $TRAVIS_BUILD_DIR;
          fi

        - gcloud -q components update

        - if [ -a client_secrets.json ]; then
                gcloud -q auth activate-service-account --key-file client_secrets.json;
          fi

        - gcloud config set project causal-flame-94214

install:
        - pip install -t lib -r requirements.txt

script:
        - gcloud -q preview app deploy app.yaml
